# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.hostName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ .Values.appName }}-service
            port:
              number: 80